### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Dmytro-Komaryst** [sindresorhus/pretty-ms#15]
Reproduced this "Bug" on the platform:
OS: Windows 7 and Windows 8.1
Windows app: Postman v4.6.1 and Postman v4.6.2
Newman v2 and v3
NodeJS v.4.5.1 and v.6.4.0

Received error for POST request (must be response "204 No Content") but I received next error:
TypeError: Expected a finite number
at module.exports (C:\Program Files\nodejs\node_modules\npm\node_modules\pretty-ms\index.js:8:9)
at C:\Program Files\nodejs\node_modules\npm\node_modules\newman\lib\reporters\html\index.js:75:27
at arrayEach (C:\Program Files\nodejs\node_modules\npm\node_modules\lodash\lodash.js:522:11)
at Function.forEach (C:\Program Files\nodejs\node_modules\npm\node_modules\lodash\lodash.js:9011:14)
at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\lib\reporters\html\index.js:67:11)
at EventEmitter.emit (C:\Program Files\nodejs\node_modules\npm\node_modules\eventemitter3\index.js:138:33)
at .assignIn.done (C:\Program Files\nodejs\node_modules\npm\node_modules\newman\lib\run\index.js:156:29)
at C:\Program Files\nodejs\node_modules\npm\node_modules\postman-runtime\lib\backpack\index.js:56:34
at PostmanCollectionRun..extend._process (C:\Program Files\nodejs\node_modules\npm\node_modules\postman-runtime\lib\runner\run.js:107:20)
at PostmanCollectionRun. (C:\Program Files\nodejs\node_modules\npm\node_modules\postman-runtime\lib\runner\run.js:118:18)

**Comment by icyflame** [comment]
Hey @Dmytro-Komaryst , I am a contributor on this module. Can you post the calling code here?

The bug clearly states that you are calling the `prettyMs` function with a number that isn't finite. Refer to [`isFinite`](https://github.com/sindresorhus/is-finite) for more info about what numbers are considered to be finite.

**Comment by sindresorhus** [comment]
This is a problem in `postman-runtime`, not this module.

**Comment by Dmytro-Komaryst** [comment]
POST
https://bo-preprod.icecat.biz/restful/v2/multimedia/31992937?link_origin=http://objects.icecat.biz/objects/mmo_33151921_1471944238_1828_24448.pdf&langid=1&fileType=getFromUrl&short_descr=1111&type=pdf&access_key=k4ihsv738eq13ghvso3v5r0r41&session_type=rest

2016-10-07 12:40 GMT+03:00 Siddharth Kannan <notifications@github.com>:

**Comment by Dmytro-Komaryst** [comment]
The link will be live 1 hour!

2016-10-07 13:00 GMT+03:00 Dmitri Komarist <d.komarist@gmail.com>:

**Comment by Dmytro-Komaryst** [comment]
Ok.

2016-10-07 13:01 GMT+03:00 Dmitri Komarist <d.komarist@gmail.com>:
